### ISSUE TITLE
Overly verbose class modifier

### ISSUE THREAD

**Issue by cubrr** [HappyZombies/Circle#1] opened 2015-07-09 18:40 UTC
Not sure if `ass` is a keyword in Java. On [line 8 of Circle.java](https://github.com/HappyZombies/Circle/blob/1e1c8a80ad4f548e6f47d6536b46a257c7f51616/src/Circle.java#L8) (protip: when looking at source code, click on the line number to get a link that leads to that line. Press `y` on the keyboard to generate a permalink to that specific version of the file).

```java
//Read this first please

//Author: HappyZombies
/*Taken from tutorial online, comments added so I myself could understand 
what is going on :) */

//Define the class
public ass Circle {   //whatever we call the file, this class must be the same
//     ^	
```

**Comment by cubrr** [comment] 2015-07-09 18:41
Oh, it's missing `cl`. Heh.

**Comment by HappyZombies** [comment] 2015-07-09 19:04
Haha! Good! I'm trying to see if there is a way to 'close' an issue. Mhmm... I'll find it eventually.

**Comment by cubrr** [comment] 2015-07-09 19:18
Usually you'd want to fix the issue before closing the issue on Github ;)

**Comment by HappyZombies** [comment] 2015-07-09 19:26
Well the issue is resolved! So let me go ahead and close it:D

**Closed** 2015-07-09 19:40 UTC
